import { StyleSheet } from 'react-native';
import { BaseColor } from '@config';

export default StyleSheet.create({
  pickerIosSty: {
    fontSize: 18,
    padding: 10,
    width: 370,
    margin: 5,
    borderRadius: 12,
    alignSelf: 'flex-start',
    borderColor: '#CCCCCC',
    backgroundColor: '#fff',
    borderWidth: 1,
    width: '80%',
  },
  pickerAndSty: {
    fontSize: 18,
    padding: 10,
    width: '100%',
  },
  pickerContainer: {
    paddingHorizontal: 5,
    backgroundColor: '#fff',
    marginTop: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderColor: '#c0c0c0',
    borderWidth: 1,
    width: '100%',
    maxWidth: 400,
  },
  container: {
    flex: 1,
    backgroundColor: '#E5E5E5',
  },
  profileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: BaseColor.textSecondaryColor,
    borderBottomWidth: 1,
    paddingBottom: 10,
    paddingTop: 10,
  },
  profile: {
    marginBottom: 20,
    marginTop: 20,
    width: 80,
    height: 80,
    borderRadius: 50,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  topCard: {
    backgroundColor: '#fff',
    paddingBottom: 20,
  },
  bottomCard: {
    marginHorizontal: 20,
  },
  name: {
    textAlign: 'center',
    color: '#0A7C53',
    fontSize: 16,
    fontWeight: 'bold',
  },
  category: {
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#535353',
  },
  cText2: {
    marginLeft: 10,
    fontSize: 14,
    color: '#535353',
  },
  dataContainer: {
    marginTop: 10,
    marginBottom: 20,
  },
  formLabel: {
    marginTop: 15,
  },
  editIcon: {
    marginLeft: 10,
  },
  buttonTextAdd: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(173, 173, 173, .6)',
  },
  modalView: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalButtonContainer: {
    flexDirection: 'column',
    marginVertical: 20,
  },
  okIcon: {
    color: '#0AB678',
    textAlign: 'center',
    marginBottom: 10,
  },
  errorIcon: {
    textAlign: 'center',
    marginBottom: 10,
    color: '#CC4344',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#CC4343',
    marginBottom: 10,
    textAlign: 'center',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  modalText: {
    fontSize: 18,
    color: '#CC4343',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  add: {
    width: '60%',
    height: 50,
    marginTop: 10,
    marginRight: 10,
    marginBottom: 100,
    padding: 12,
    borderRadius: 20,
    alignSelf: 'center',
  },
  activityBox: {
    backgroundColor: '#c0c0c0',
    borderRadius: 12,
    padding: 15,
    marginVertical: 2,
  },
  kycContainer: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 55,
  },
});
