import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
  },
  notiContainer: {
    marginBottom: 20,
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  card: {
    backgroundColor: '#fff',
    paddingLeft: 25,
    paddingRight: 25,
    paddingTop: 10,
    alignItems: 'center',
  },
  imageContainer: {
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 1, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 7,
    elevation: 6,
    marginBottom: 15,
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: '#fff',
  },
  name: {
    textAlign: 'center',
    marginRight: 20,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0A5C3E',
  },
  ageContainer: {
    paddingBottom: 20,
  },
  age: {
    textAlign: 'center',
    marginTop: 2,
    fontSize: 14,
    color: '#A2A2A2',
  },
  icon: {
    fontSize: 18,
    width: 25,
    color: '#0A5C3E',
  },
  riskTitle: {
    alignItems: 'flex-start',
    fontSize: 14,
    lineHeight: 26,
    color: '#575757',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  todayTitle: {
    alignItems: 'flex-start',
    fontSize: 16,
    lineHeight: 26,
    color: '#575757',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  mainContainer: {
    marginTop: 25,
    marginLeft: 10,
    marginRight: 10,
  },
  resultContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    flexWrap: 'wrap',
  },
  walkContainer: {
    flex: 1,
    marginBottom: 25,
  },
  resultBox: {
    // height: '50%',
    width: '31%',
    marginLeft: 2,
    marginRight: 2,
    marginBottom: 20,
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 1, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 8,
  },
  emptyBox: {
    // height: '50%',
    width: '31%',
    marginLeft: 2,
    marginRight: 2,
    marginBottom: 20,
    padding: 10,
  },
  walkBox: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 1, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 8,
  },
  resultTitle: {
    alignSelf: 'flex-start',
    fontSize: 14,
    color: '#575757',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  valueContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  progress: {
    flex: 1,
    backgroundColor: '#fff',
  },
  bar: {
    marginHorizontal: 10,
  },
  resultValue: {
    color: '#095394',
    fontWeight: 'bold',
    fontSize: 18,
  },
  image: {
    width: 25,
    height: 25,
    resizeMode: 'cover',
    marginRight: 10,
  },
  boxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
    flexWrap: 'wrap',
  },
  alertContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
    marginBottom: 20,
  },
  alertImage: {
    width: 35,
    height: 35,
    resizeMode: 'cover',
    marginRight: 10,
  },
  alertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
    marginBottom: 20,
    height: 40,
    width: '75%',
    marginRight: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 1, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 8,
  },
  drugBox: {
    alignItems: 'flex-start',
    height: 100,
    width: '27%',
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 20,
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 1, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 8,
  },
  innerBox: {
    width: '100%',
    flex: 1,
  },
  topInner: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  imageDrug: {
    width: '100%',
    height: 40,
    resizeMode: 'contain',
  },
  smallText: {
    fontSize: 9,
  },
  mediumText: {
    fontSize: 12,
  },
  IconFit: {
    width: 45,
    height: 45,
  },
  cardFitContainer: {
    borderRadius: 15,
    overflow: 'hidden',
    maxWidth: 380,
    alignSelf: 'center',
  },
  cardFitWrapper: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerTextFit: {
    flex: 1,
    marginLeft: 7,
  },
  textFit: {
    color: '#222',
    fontSize: 13,
  },
});

export default styles;
