import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  topContainer: {
    backgroundColor: 'white',
    shadowColor: '#000',
    elevation: 3,
    paddingHorizontal: 20,
  },
  topBlock: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  titleIcon: {
    fontSize: 16,
    marginRight: 8,
    color: '#40424B',
  },
  titleText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#40424B',
  },
  signInGradient: {
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 3.84,
    elevation: 6,
    flex: 1,
    marginHorizontal: 10,
    marginBottom: 20,
  },
  buttonContainer: {
    width: '100%',
    marginBottom: 20,
  },
  buttonConfirmContainer: {
    width: '100%',
    marginVertical: 10,
  },
  button: {
    borderRadius: 12,
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 15,
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: '#FFFFFF',
  },
  presListTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
    marginHorizontal: 20,
    fontSize: 20,
    color: '#40424B',
  },
  presListHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
    marginBottom: 10,
  },
  presName: {
    flex: 1,
    color: '#40424B',
    marginRight: 5,
  },
  instructions: {
    marginLeft: 20,
    marginBottom: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0, .6)',
  },
  modalView: {
    width: '70%',
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    paddingBottom: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  openButton: {
    //     backgroundColor: '#CC4344',
    marginTop: 15,
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  textConfirm: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  textCancel: {
    color: 'black',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  modalSuccessTitle: {
    marginBottom: 15,
    color: '#0A5C3E',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 22,
  },
  modalFailTitle: {
    marginBottom: 15,
    color: 'red',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 22,
  },
  presListHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
    marginBottom: 10,
  },
  modalText: {
    fontSize: 18,
    color: '#CC4343',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#CC4343',
    marginBottom: 10,
    textAlign: 'center',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  buttonTextAdd: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalRowContainer: {
    flexDirection: 'row',
    marginVertical: 5,
    marginHorizontal: 10,
  },
  modalButton: {
    flex: 1,
    width: '100%',
    height: 50,
    marginTop: 10,
    marginHorizontal: 10,
    marginBottom: 100,
    padding: 12,
    borderRadius: 20,
    alignSelf: 'center',
  },
  textConfirm: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
});

export default styles;
