export default tempDrugs = [
  {
    drugId: '5010000402',
    name: 'AFTER MEAL MORNING EVENING',
    qty: 20,
    usedQty: 2,
    drugUsage: 'ฉีดเข้าใต้ผิวหนัง ครั้งละ 60 MG.  ทุก 6 เดือน',
    medusetime: '2P',
    medusetime_name: 'Q6MO',
    status: true,
    id: 1,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 26,
    drugComplianceType: {
      name: '2P',
      detail: 'วันละ 2 ครั้ง หลังอาหารเช้า เย็น',
      timeperday: 2,
      logic: ['AM', 'AE'],
      id: 26,
    },
  },
  {
    drugId: '5010000158',
    name: 'CALCIFEROL 20000 IUCAPSULE',
    qty: 10,
    usedQty: 11,
    drugUsage: 'รับประทาน ครั้งละ 1 แคปซูล สัปดาห์ละ 1 ครั้ง',
    medusetime: 'OW',
    medusetime_name: 'สัปดาห์ละ 1 ครั้ง',
    status: true,
    id: 2,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: null,
  },
  {
    drugId: '5010000444',
    name: 'AFTER MEAL 4 TIMES',
    qty: 5,
    usedQty: 0,
    drugUsage: 'ดื่ม ครั้งละ 120 MG.',
    medusetime: 'PBLDS',
    medusetime_name: 'ทุกมื้อ',
    status: true,
    id: 3,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 27,
    drugComplianceType: {
      name: 'PBLDS',
      detail: 'วันละ 4 ครั้ง หลังอาหารเช้า กลางวัน เย็น ก่อนนอน',
      timeperday: 4,
      logic: ['AM', 'AL', 'AE', 'B'],
      id: 27,
    },
  },
  {
    drugId: '5010000444',
    name: 'AFTER MEAL 4 TIMES [2!!]',
    qty: 5,
    usedQty: 0,
    drugUsage: 'ดื่ม ครั้งละ 120 MG.',
    medusetime: 'PBLDS',
    medusetime_name: 'ทุกมื้อ',
    status: true,
    id: 4,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 28,
    drugComplianceType: {
      name: 'PBLDS',
      detail: 'วันละ 4 ครั้ง หลังอาหารเช้า กลางวัน เย็น ก่อนนอน',
      timeperday: 4,
      logic: ['AM', 'AL', 'AE', 'B'],
      id: 28,
    },
  },
  {
    drugId: '5010000445',
    name: 'BEFORE MORNING MEAL',
    qty: 2,
    usedQty: 0,
    drugUsage: 'กิน ครั้งละ 1 เม็ด.',
    medusetime: '1A',
    medusetime_name: '2 ครั้ง',
    status: true,
    id: 5,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 29,
    drugComplianceType: {
      name: '1A',
      detail: 'วันละ 1 ครั้ง ก่อนอาหารเช้า',
      timeperday: 1,
      logic: ['BM'],
      id: 29,
    },
  },
  {
    drugId: '5010000445',
    name: 'BEFORE BED',
    qty: 2,
    usedQty: 0,
    drugUsage: 'กิน ครั้งละ 1 เม็ด.',
    medusetime: 'B',
    medusetime_name: '2 ครั้ง',
    status: true,
    id: 6,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 30,
    drugComplianceType: {
      name: '1A',
      detail: 'วันละ 1 ครั้ง ก่อนอาหารเช้า',
      timeperday: 1,
      logic: ['B'],
      id: 30,
    },
  },
  {
    drugId: '5010000446',
    name: 'AFTER MEAL ONLY MORNING',
    qty: 5,
    usedQty: 0,
    drugUsage: 'ดื่ม ครั้งละ 120 MG.',
    medusetime: 'PBLDS',
    medusetime_name: 'หลังอาหารเช้า',
    status: true,
    id: 7,
    userId: 10,
    prescriptionId: 7,
    drugComplianceTypeId: 31,
    drugComplianceType: {
      name: 'AM',
      detail: 'หลังอาหารเช้า',
      timeperday: 4,
      logic: ['AM'],
      id: 31,
    },
  },
];
