import { StyleSheet, Platform } from 'react-native';
import { BaseColor } from '@config';

export default StyleSheet.create({
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ccc',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
  },
  illustration: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
    backgroundColor: '#F3FFFB',
  },
  contentContainer: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 10,
  },
  contentTitle: {
    fontSize: 26,
    fontWeight: 'bold',
  },
  contentSubtitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  contentDetail: {
    fontSize: 16,
    color: '#535353',
    marginVertical: 15,
  },
  lineContainer: {
    marginVertical: 10,
    flexDirection: 'row',
  },
  line: {
    backgroundColor: '#000',
    height: 1,
    flex: 1,
    alignSelf: 'center',
  },
  profileImageContainer: {
    shadowColor: 'grey',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 6,
    borderRadius: 35,
  },
  profileImage: {
    width: 50,
    height: 50,
  },
  wrapName: {
    flexDirection: 'row',
    width: '88%',
  },
  doctorName: {
    color: '#0A5C3E',
    marginLeft: 20,
    fontSize: 16,
    flex: 1,
    fontWeight: 'bold',
  },
  doctorProfile: {
    flexDirection: 'row',
    flex: 1,
    marginLeft: 20,
    marginVertical: 2,
  },
  doctorText: {
    fontSize: 14,
    flex: 1,
  },
  detailIcon: {
    fontSize: 12,
    marginRight: 8,
    color: '#535353',
  },
  detailText: {
    fontSize: 12,
    color: '#535353',
  },
  makeRow: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
    marginVertical: 5,
  },
  timeIcon: {
    fontSize: 18,
    marginRight: 8,
    color: '#535353',
  },
  timeText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#535353',
  },
  appointmentContainer: {
    marginLeft: 25,
    color: '#0DB779',
    marginBottom: 5,
    flexDirection: 'row',
    alignSelf: 'flex-start',
  },
  appoitnmentText: {
    color: '#535353',
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  buttonItem: {
    backgroundColor: '#fff',
    width: '31%',
    margin: 10,
    paddingHorizontal: 10,
    paddingTop: 20,
    paddingBottom: 10,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
  },
  buttonGreenText: {
    fontSize: 12,
    color: '#09B678',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonWhiteText: {
    fontSize: 12,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonGreenIcon: {
    width: 50,
    height: 50,
  },
  buttonWhiteIcon: {
    width: 50,
    height: 50,
  },
  mainIconContainer: {
    width: '100%',
    height: 180,
    resizeMode: 'cover',
    position: 'absolute',
    zIndex: -1,
  },
  textContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
  },
  title: {
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 25,
    color: '#535353',
    fontSize: 18,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 16,
    color: '#095C3E',
    fontWeight: 'bold',
  },
  content: {
    marginLeft: 15,
    fontSize: 14,
    color: '#5E5E5E',
  },
  content2: {
    fontSize: 14,
    color: '#5E5E5E',
  },
  space: {
    marginVertical: 8,
  },
  contentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: '#fff',
  },
  contentTitle: {
    fontSize: 26,
    textAlign: 'center',
    color: '#09B678',
    fontWeight: 'bold',
    marginBottom: 10,
    marginVertical: 15,
  },
  contentDetail: {
    fontSize: 16,
    textAlign: 'center',
    color: '#535353',
    marginVertical: 15,
  },
  card: {
    borderRadius: 14,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
  },
  nextButton: {
    borderRadius: 22,
    paddingHorizontal: 40,
    marginVertical: 5,
    elevation: 2,
    backgroundColor: '#09B678',
    padding: 15,
  },
  nextStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 20,
  },
  paginationContainer: {
    backgroundColor: '#fff',
    paddingVertical: 5,
  },
  smallText: {
    textAlign: 'right',
    marginRight: 10,
    marginBottom: 10,
    color: '#c0c0c0',
  },
  directionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
  },
  before: { backgroundColor: '#fff', paddingLeft: 5 },
  next: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'flex-end',
  },
  whiteBG: {
    backgroundColor: '#fff',
  },
});
