export const CREATE_BOOKING_REQUEST = 'app/Booking/CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_FAILURE = 'app/Booking/CREATE_BOOKING_FAILURE';
export const CREATE_BOOKING_SUCCESS = 'app/Booking/CREATE_BOOKING_SUCCESS';

export const GET_BOOKING_REQUEST = 'app/Booking/GET_BOOKING_REQUEST';
export const GET_BOOKING_FAILURE = 'app/Booking/GET_BOOKING_FAILURE';
export const GET_BOOKING_SUCCESS = 'app/Booking/GET_BOOKING_SUCCESS';
