export const GET_BOOKINGS_REQUEST = 'app/Bookings/GET_BOOKINGS_REQUEST';
export const GET_DOCTOR_BOOKINGS_REQUEST =
  'app/Bookigns/GET_DOCTOR_BOOKINGS_REQUEST';
export const GET_BOOKINGS_FAILURE = 'app/Bookings/GET_BOOKINGS_FAILURE';
export const GET_BOOKINGS_SUCCESS = 'app/Bookings/GET_BOOKINGS_SUCCESS';
