export const CREATE_CHAT_REQUEST = 'app/Chat/CREATE_CHAT_REQUEST';
export const CREATE_CHAT_FAILURE = 'app/Chat/CREATE_CHAT_FAILURE';
export const CREATE_CHAT_SUCCESS = 'app/Chat/CREATE_CHAT_SUCCESS';
