export const GET_DOCTOR_REQUEST = 'app/DOCTOR/GET_DOCTOR_REQUEST';
export const GET_DOCTOR_SUCCESS = 'app/DOCTOR/GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILURE = 'app/DOCTOR/GET_DOCTOR_FAILURE';
