export const GET_USER_TELE_REQUEST = 'app/User/GET_USER_TELE_REQUEST';
export const GET_USER_TELE_SUCCESS = 'app/User/GET_USER_TELE_SUCCESS';
export const GET_USER_TELE_FAILURE = 'app/User/GET_USER_TELE_FAILURE';

export const LOGOUT_REQUEST = 'app/User/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'app/User/LOGOUT_SUCCESS';
