import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingBottom: 20,
    marginBottom: 20,
  },
  listContainer: {
    padding: 20,
    backgroundColor: '#fff',
  },
  dataContainer: {
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  left: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftTime: {
    flex: 1,
    flexDirection: 'row',
  },
  right: {
    justifyContent: 'center',
  },
  image: {
    width: 25,
    height: 25,
    resizeMode: 'cover',
    marginRight: 10,
  },
  leftText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  rightText: {
    color: '#095394',
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  leftValue: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#535353',
  },
  leftMeasurement: {
    fontSize: 14,
    fontWeight: 'normal',
    color: '#535353',
  },
  result: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  lineContainer: {
    marginVertical: 3,
    flexDirection: 'row',
  },
  line: {
    backgroundColor: '#E5E5E5',
    height: 1,
    flex: 1,
    alignSelf: 'center',
  },
  add: {
    flex: 1,
    width: '100%',
    height: 50,
    marginTop: 10,
    padding: 12,
    borderRadius: 20,
    alignSelf: 'center',
  },
  delete: {
    flex: 1,
    width: '100%',
    height: 50,
    marginTop: 10,
    padding: 12,
    alignSelf: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#c0c0c0',
  },
  buttonTextAdd: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonTextDelete: {
    color: '#CC4343',
    fontSize: 18,
    fontWeight: 'bold',
  },
  calendar: {
    fontSize: 18,
    marginLeft: 5,
    marginRight: 14,
    color: '#535353',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(217, 237, 208, .6)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalActivity: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 40,
    paddingTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  activityContainer: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 12,
    padding: 20,
    marginVertical: 10,
  },
  activityBox: {
    backgroundColor: '#c0c0c0',
    borderRadius: 12,
    padding: 15,
    marginVertical: 2,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
  },
  yesButton: {
    backgroundColor: '#fff',
    marginTop: 15,
    marginRight: 20,
    borderRadius: 16,
    paddingHorizontal: 40,
    paddingVertical: 15,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#c0c0c0',
  },
  noButton: {
    backgroundColor: '#CC4343',
    marginTop: 15,
    borderRadius: 16,
    paddingHorizontal: 50,
    paddingVertical: 15,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#c0c0c0',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#CC4343',
    marginBottom: 10,
    textAlign: 'center',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  modalText: {
    fontSize: 14,
    color: '#CC4343',
    textAlign: 'center',
  },
});

export default styles;
