import React from 'react';
import { StyleSheet, Platform } from 'react-native';
import { BaseColor } from '@config';
import * as Utils from '@utils';

export default StyleSheet.create({
  btnContainer: {
    marginHorizontal: 10,
    height: 50,
    marginTop: 40,
    marginBottom: 40,
    borderWidth: 1,
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'grey',
    borderColor: '#284F30',
    borderRadius: 60,
    alignSelf: 'center',
    flex: 1,
  },
  imgBanner: {
    width: '100%',
    height: 250,
    position: 'absolute',
  },
  blockView: {
    marginHorizontal: 10,
    paddingVertical: 10,
    borderBottomColor: BaseColor.textSecondaryColor,
    borderBottomWidth: 1,
  },
  contentService: {
    paddingVertical: 10,
    borderBottomColor: BaseColor.textSecondaryColor,
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  contentBoxTop: {
    padding: 5,
    marginTop: 100,
    // height: 120,
    width: '100%',
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 0,
    // backgroundColor: BaseColor.whiteColor,
    // shadowOffset: { width: 3, height: 3 },
    // shadowColor: BaseColor.grayColor,
    // shadowOpacity: 1.0,
    // elevation: 5
  },
  circlePoint: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 5,
    backgroundColor: BaseColor.primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentRateDetail: {
    flexDirection: 'row',
    paddingTop: 20,
  },
  lineBaseRate: {
    width: '100%',
    height: 12,
    borderRadius: 8,
    backgroundColor: BaseColor.textSecondaryColor,
  },
  linePercent: {
    width: '80%',
    height: 12,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    backgroundColor: BaseColor.accentColor,
    position: 'absolute',
    bottom: 0,
  },
  contentLineRate: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  listContentIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    width: '100%',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  itemReason: {
    paddingLeft: 10,
    marginTop: 10,
    flexDirection: 'row',
  },
  contentButtonBottom: {
    borderTopColor: BaseColor.textSecondaryColor,
    borderTopWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  lineContainer: {
    marginVertical: 15,
    flexDirection: 'row',
  },
  line: {
    backgroundColor: '#E5E5E5',
    height: 1,
    flex: 1,
    alignSelf: 'center',
  },
  doctorProfile: {
    flexDirection: 'row',
    flex: 1,
    marginLeft: 20,
    marginVertical: 2,
  },
  doctorText: {
    fontSize: 14,
    flex: 1,
  },
  doctorName: {
    color: '#0A5C3E',
    marginLeft: 20,
    fontSize: 16,
    flex: 1,
    fontWeight: 'bold',
  },
  userIcon: {
    fontSize: 20,
    width: 25,
    height: 25,
    color: '#535353',
  },
  userAva: {
    shadowColor: 'grey',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 15,
  },
  makeRow: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  titleIcon: {
    fontSize: 16,
    marginRight: 8,
    color: '#085394',
  },
  titleText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#085394',
  },
  status: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginLeft: 20,
  },
  statusIcon: {
    width: 10,
    height: 10,
    marginRight: 5,
    borderRadius: 50,
  },
  statusText: {
    fontSize: 11,
  },
  detailIcon: {
    fontSize: 12,
    marginRight: 8,
    color: '#535353',
  },
  detailText: {
    fontSize: 12,
    color: '#535353',
  },
  wrapName: {
    flexDirection: 'row',
    width: '88%',
  },
  timeIcon: {
    fontSize: 18,
    marginRight: 8,
    color: '#535353',
  },
  timeText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#535353',
  },
  confirmText: {
    color: '#0DB779',
    fontWeight: 'bold',
  },
  confirmTextContainer: {
    display: 'flex',
    flex: 1,
    alignItems: 'flex-end',
  },
  appointmentContainer: {
    marginLeft: 25,
    color: '#0DB779',
    marginBottom: 10,
    flexDirection: 'row',
    alignSelf: 'flex-start',
  },
  appoitnmentText: {
    color: '#535353',
    fontSize: 16,
  },
  buttonGroupContainer: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: 'white',
  },
  buttonAllowContainer: {
    height: 50,
    marginTop: 10,
    alignItems: 'center',
    padding: 12,
    borderRadius: 20,
    alignSelf: 'center',
    flex: 1,
  },
  buttonNotAllowContainer: {
    height: 50,
    marginTop: 10,
    borderWidth: 1,
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'grey',
    borderColor: 'grey',
    borderRadius: 20,
    alignSelf: 'center',
    flex: 1,
  },
  buttonMassageContainer: {
    height: 50,
    marginTop: 10,
    borderWidth: 1,
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'white',
    borderColor: 'black',
    borderRadius: 20,
    alignSelf: 'center',
    flex: 1,
    width: '100%',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonTextBlack: {
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
  },
  footnoteContainer: {
    alignItems: 'center',
    marginHorizontal: 20,
  },
  footnote: {
    fontSize: 14,
    marginRight: 8,
    color: '#A62828',
  },
  massageButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 35,
  },
  massageIcon: {
    fontSize: 27,
  },
});
