import { StyleSheet } from 'react-native';
import { BaseColor } from '@config';
import * as Utils from '@utils';

export default StyleSheet.create({
  imageBackground: {
    height: 140,
    width: '100%',
    position: 'absolute',
  },
  linearGradient: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingLeft: 15,
    paddingTop: 15,
  },
  eventCard: {
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 6,
    shadowColor: '#000',
    backgroundColor: 'white',
  },
  thumb: {
    backgroundColor: '#fff',
    width: 60,
    height: 60,
    borderRadius: 50,
    marginBottom: 20,
  },
  searchForm: {
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BaseColor.fieldColor,
    backgroundColor: BaseColor.whiteColor,
    width: '90%',
    shadowColor: 'black',

    elevation: 10,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'black',
    shadowOpacity: 0.2,
  },
  textSearch: {
    color: '#7d7d7d',
    fontWeight: '600',
    fontSize: 18,
  },
  contentCartPromotion: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  btnPromotion: {
    height: 25,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
    margin: 10,
  },
  contentHiking: {
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 10,
  },
  promotionBanner: {
    height: Utils.scaleWithPixel(250),
    width: '100%',
    marginTop: 10,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  line: {
    height: 1,
    backgroundColor: BaseColor.textSecondaryColor,
    marginTop: 10,
    marginBottom: 20,
  },
  mainCard: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 6,
    shadowColor: '#000',
    backgroundColor: 'white',
  },
  iconParent: {
    // width: '18%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    marginTop: 25,
  },
  justHeader: {
    color: 'black',
    fontSize: 16,
    marginLeft: 20,
    marginTop: 20,
  },
  newsCards: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 14,
  },
  newsImage: {
    width: 150,
    height: 100,
    marginBottom: 10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  map: {
    // ...StyleSheet.absoluteFillObject,
    marginTop: 10,
    marginBottom: 5,
    marginHorizontal: 20,
    width: '90%',
    height: 150,
  },
  locationContainer: {
    flexDirection: 'row',
    marginVertical: 5,
    marginHorizontal: 20,
  },
  contentServiceIcon: {
    marginRight: 20,
    display: 'flex',
    alignItems: 'center',
  },
  iconTopAppointment: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    flex: 1,
    alignItems: 'center',
    marginBottom: 14,
    marginTop: 14,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 2,
    shadowColor: '#000',
    backgroundColor: '#284F30',
    marginHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 30,
  },
  iconTopParentAmbulance: {
    flex: 0.9,
    alignItems: 'center',
    marginBottom: 14,
    marginTop: 14,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 6,
    shadowColor: '#000',
    backgroundColor: 'white',
    marginHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 30,
  },
  iconTopParent: {
    width: '43%',
    height: 125,
    // alignItems: 'center',
    marginTop: 17,
    marginBottom: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 6,
    shadowColor: '#000',
    // backgroundColor: '#09B678',
    marginHorizontal: 10,
    borderRadius: 10,
    overflow: 'hidden',
    // paddingVertical: 30,
  },
  mainIconContainer: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'flex-end',
  },
  mainTextContainer: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  mainGradient: {
    paddingVertical: 5,
  },
  iconContent: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    borderRadius: 16,
    backgroundColor: BaseColor.fieldColor,
    marginBottom: 10,
  },
  promotionItem: {
    borderRadius: 8,
    width: Utils.scaleWithPixel(200),
    height: Utils.scaleWithPixel(250),
  },
  clinicPackageItem: {
    borderRadius: 8,
    width: Utils.scaleWithPixel(135),
    height: Utils.scaleWithPixel(160),
  },
  iconContentMany: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 50,
    borderRadius: 18,
    // backgroundColor: BaseColor.fieldColor
  },
  itemServiceMany: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    width: '43%',
    height: 100,
  },
  contentServiceIconMany: {
    flex: 1,
    width: '45%',
    marginTop: 10,
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  modalContent: {
    flex: 1,
    padding: 10,
  },
  modalToggle: {
    padding: 10,
    borderRadius: 10,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#bbded6',
  },
  selectButton: {
    borderRadius: 5,
    width: 150,
    height: 50,
    backgroundColor: '#8ac6d1',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 120,
  },
  uploadButton: {
    borderRadius: 5,
    width: 150,
    height: 50,
    backgroundColor: '#ffb6b9',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  imageContainer: {
    marginTop: 30,
    marginBottom: 50,
    alignItems: 'center',
  },
  progressBarContainer: {
    marginTop: 20,
  },
  imageBox: {
    width: 300,
    height: 300,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(173, 173, 173, .6)',
  },
  modalView: {
    width: '70%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalButtonContainer: {
    flexDirection: 'column',
    marginVertical: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#CC4344',
    marginBottom: 10,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  add: {
    width: '100%',
    marginTop: 10,
    padding: 12,
    borderRadius: 20,
  },
  buttonTextAdd: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  paymentTitle: {
    fontWeight: 'bold',
    color: '#062d38',
  },
  paymentText: {},
  paymentAlert: {
    flexDirection: 'row',
    padding: 20,
    marginTop: 15,
    width: '90%',
    backgroundColor: '#a0eaff',
    alignSelf: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
  },
  paymentButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
});
