import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
    marginBottom: 10,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 20,
    width: '60%',
    backgroundColor: '#f2f2f2',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 12,
    overflow: 'hidden',
  },
  mainContainer: {
    marginTop: 10,
    marginLeft: 20,
    marginRight: 10,
  },
  title: {
    textAlign: 'left',
    fontSize: 16,
    lineHeight: 26,
    color: '#575757',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  androidText: {
    textAlign: 'left',
    fontSize: 16,
    lineHeight: 26,
    color: '#575757',
  },
  androidSetTime: {
    width: '61%',
    marginHorizontal: 20,
    height: 60,
    padding: 15,
    paddingHorizontal: 40,
    marginVertical: 20,
    borderRadius: 12,
  },
  take: {
    // flex: 1,
    // width: '100%',
    marginHorizontal: 20,
    height: 60,
    padding: 15,
    paddingHorizontal: 40,
    marginVertical: 20,
    borderRadius: 12,
    alignSelf: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(173, 173, 173, .6)',
  },
  modalView: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalButtonContainer: {
    flexDirection: 'column',
    marginVertical: 20,
  },
  add: {
    width: '100%',
    height: 50,
    marginTop: 10,
    marginRight: 10,
    marginBottom: 100,
    padding: 12,
    borderRadius: 20,
    alignSelf: 'center',
  },
  okIcon: {
    color: '#0AB678',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalText: {
    fontSize: 18,
    color: '#CC4343',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  modalSText: {
    fontSize: 18,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#CC4343',
    marginBottom: 10,
    textAlign: 'center',
    shadowColor: '#c0c0c0',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  buttonTextAdd: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default styles;
