import React from 'react';
import { StyleSheet } from 'react-native';
import { BaseColor, Typography, FontWeight } from '@config';

export default StyleSheet.create({
  pickerIosSty: {
    fontSize: 18,
    padding: 10,
    width: 370,
    margin: 5,
    borderRadius: 12,
    alignSelf: 'flex-start',
    borderColor: '#CCCCCC',
    backgroundColor: '#fff',
    borderWidth: 1,
    width: '80%',
  },
  pickerAndSty: {
    fontSize: 18,
    padding: 10,
    width: '100%',
  },
  pickerContainer: {
    paddingHorizontal: 5,
    backgroundColor: '#fff',
    marginTop: 10,
    borderRadius: 12,
    borderColor: '#c0c0c0',
    borderWidth: 1,
    width: '100%',
    maxWidth: 400,
  },
  backStepButton: {
    alignSelf: 'center',
    width: 60,
    height: 60,
    borderRadius: 50,
    backgroundColor: 'white',
    top: 10,
    left: 10,
    position: 'absolute',
    justifyContent: 'center',
  },
  takePhotoButton: {
    alignSelf: 'center',
    width: 80,
    height: 80,
    borderRadius: 50,
    backgroundColor: 'white',
    bottom: 20,
    position: 'absolute',
    justifyContent: 'center',
  },
  addShadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,

    elevation: 11,
  },
  addShadowButton: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.36,
    shadowRadius: 6.68,

    elevation: 11,
    borderRadius: 100,
    width: 100,
    height: 100,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textInput: {
    height: 56,
    backgroundColor: 'white',
    borderRadius: 5,
    marginTop: 10,
    padding: 10,
    width: '100%',
    marginHorizontal: 10,
  },
  contain: {
    flex: 1,
    padding: 20,
    paddingTop: 10,
    width: '100%',
    backgroundColor: '#F5F5F5',
  },
  default: {
    height: 56,
    borderRadius: 28,
    backgroundColor: '#5c9cff',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  selectButton: {
    borderRadius: 100,
    width: 100,
    height: 100,
    backgroundColor: 'white',
    borderColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  uploadButton: {
    borderRadius: 5,
    width: 150,
    height: 50,
    backgroundColor: '#ffb6b9',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    alignSelf: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
  },
  textDefault: {
    ...Typography.headline,
    color: BaseColor.whiteColor,
    fontWeight: FontWeight.semibold,
  },
  outline: {
    backgroundColor: BaseColor.whiteColor,
    borderWidth: 1,
    borderColor: BaseColor.primaryColor,
  },
  textOuline: {
    color: BaseColor.primaryColor,
  },
  full: {
    width: '100%',
  },
  round: {
    borderRadius: 28,
  },
  progressBarContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linearGradient: {
    backgroundColor: '#0A7C53',
    borderBottomLeftRadius: 19,
    borderBottomRightRadius: 19,
    paddingBottom: 8,
    paddingTop: 8,
  },
  signInGradient: {
    borderRadius: 18,
  },
  container: {
    marginBottom: 35,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  radioText: {
    marginRight: 35,
    fontSize: 16,
    color: '#000',
    fontWeight: '700',
  },
  radioCircle: {
    height: 20,
    width: 20,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: '#3740ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedRb: {
    width: 15,
    height: 15,
    borderRadius: 50,
    backgroundColor: '#3740ff',
  },
  result: {
    marginTop: 20,
    color: 'white',
    fontWeight: '600',
    backgroundColor: '#F3FBFE',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0, .6)',
  },
  modalView: {
    flex: 1,
    paddingTop: 50,
    backgroundColor: 'white',
    padding: 20,
    alignItems: 'center',
  },
  modalViewSuccess: {
    flex: 1,
    margin: 0,
    backgroundColor: 'white',
  },
  openButton: {
    backgroundColor: '#CC4344',
    marginTop: 15,
    borderRadius: 22,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalComplianceTitle: {
    marginBottom: 20,
    color: '#0A5C3E',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  modalSubtitle: {
    marginBottom: 15,
    color: '#0A5C3E',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  modalSuccessTitle: {
    marginBottom: 10,
    color: '#0A5C3E',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 26,
  },
  modalFailureTitle: {
    marginBottom: 15,
    color: '#CC4344',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 26,
  },
  modalText: {
    marginBottom: 3,
    textAlign: 'center',
  },
  congratsContainer: {
    padding: 20,
    alignItems: 'center',
  },
  thankyouContainer: {
    flex: 1,
    backgroundColor: '#E5E5E5',
    marginTop: 20,
    paddingTop: 20,
  },
});
